name: weather_app
description:
  "A weather application that provides current conditions and forecasts based on
  user location or search."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.0
  flutter: ">=3.27.0"

dependencies:
  connectivity_plus: ^6.1.3
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_dotenv: ^5.2.1
  flutter_localizations:
    sdk: flutter
  get_it: ^8.0.3
  go_router: ^14.8.1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  objectbox: ^4.1.0
  objectbox_flutter_libs: ^4.1.0
  path: ^1.8.0
  path_provider: ^2.1.0
  stream_transform: ^2.1.1

dev_dependencies:
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.0
  objectbox_generator: ^4.1.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - .env
